insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (1, 'Dorelle', 'Davsley', 'ddavsley0@jalbum.net', '558-389-1527', 'Executive Secretary', 147);
insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (2, 'Idalia', 'Arthey', 'iarthey1@amazon.co.jp', '170-902-4292', 'Analog Circuit Design manager', 174);
insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (3, 'Nydia', 'Ilott', 'nilott2@google.es', '337-365-4205', 'Senior Cost Accountant', 184);
insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (4, 'Eudora', 'Batalini', 'ebatalini3@zdnet.com', '460-897-0705', 'Account Representative I', 112);
insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (5, 'Kory', 'Causier', 'kcausier4@deviantart.com', '546-401-0726', 'Structural Engineer', 201);
insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (6, 'Leicester', 'Misson', 'lmisson5@purevolume.com', '478-508-7184', 'VP Accounting', 279);
insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (7, 'Anestassia', 'Le Pruvost', 'alepruvost6@va.gov', '751-441-0319', 'Quality Engineer', 180);
insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (8, 'Rafferty', 'Peatman', 'rpeatman7@skype.com', '703-619-6107', 'Geologist III', 219);
insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (9, 'Marvin', 'Dumsday', 'mdumsday8@themeforest.net', '608-963-1626', 'Statistician I', 213);
insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (10, 'Philipa', 'Syrad', 'psyrad9@indiatimes.com', '945-644-0079', 'Clinical Specialist', 253);
insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (11, 'Prissie', 'Atkirk', 'patkirka@paypal.com', '617-931-8006', 'Staff Accountant II', 186);
insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (12, 'Nichole', 'Davidai', 'ndavidaib@instagram.com', '996-576-1136', 'Electrical Engineer', 85);
insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (13, 'Audry', 'Krolik', 'akrolikc@photobucket.com', '235-952-3842', 'Assistant Media Planner', 179);
insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (14, 'Leona', 'Moyer', 'lmoyerd@simplemachines.org', '175-596-9407', 'Geological Engineer', 62);
insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (15, 'Arliene', 'Bellis', 'abellise@tiny.cc', '466-448-3043', 'Sales Representative', 122);
insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (16, 'Pasquale', 'Barlass', 'pbarlassf@usda.gov', '392-438-2445', 'Legal Assistant', 49);
insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (17, 'Nanette', 'Prinne', 'nprinneg@ft.com', '994-472-1784', 'Marketing Assistant', 53);
insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (18, 'Archaimbaud', 'Haggett', 'ahaggetth@reddit.com', '835-385-1488', 'Research Associate', 277);
insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (19, 'Eva', 'Tubby', 'etubbyi@pen.io', '928-683-7377', 'Account Coordinator', 210);
insert into personnels (id, name_first, name_last, email, phone, job_title, office_number) values (20, 'Dagmar', 'Gelling', 'dgellingj@discuz.net', '874-220-9234', 'Product Engineer', 185);
